server.port: 8999
logging:
  file: futrues-lay-jpa/logs/log.log
#view
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false #关闭缓存
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/futrues-jpa?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: qwe123
    tomcat.max-active: 100
    tomcat.max-idle: 200
    tomcat.initialSize: 20
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 8
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1